"use node";

import { v } from "convex/values";
import OpenAI from "openai";
import { zodResponseFormat } from "openai/helpers/zod";
import { z } from "zod";
import { internalAction } from "./_generated/server";
import { internal } from "./_generated/api";
// Note: queries/mutations cannot live in "use node" files. The companion
// internalQuery `_getLookup` lives in `lookups.ts`.

/**
 * Search providers for the lookup pipeline.
 *
 * Phase 0: take a raw input string, pull the broadest set of plausible
 * references from the web, and write each result row as a `signal` so the
 * synthesis layer (and the UI's progress view) can see them stream in.
 *
 * Three providers run concurrently for discovery-style ("query") lookups:
 *
 *  - Parallel.ai Search (POST /v1beta/search): web-wide research grade
 *    search with Google-operator support. We ask an LLM to plan 12-20
 *    diverse queries, chunk them into batches of 5, and fire multiple
 *    Parallel.ai calls in parallel.
 *
 *  - Unipile LinkedIn Search (POST /api/v1/linkedin/search): LinkedIn
 *    Classic people search via the user's connected LinkedIn account.
 *    Uses a smaller, LinkedIn-boolean-syntax keyword set generated by
 *    the same LLM planner. One call per keyword.
 *
 *  - Exa People Search (POST /search with category="people"): hybrid
 *    retrieval over Exa's 1B+ indexed public profiles. Takes natural
 *    language queries ("VP of Product at Microsoft") rather than
 *    operators or booleans, so it gets its own planner output.
 *
 * Results from all three providers are merged, deduped by public URL,
 * then written as signals. The Unipile and Exa branches are best-effort:
 * if their env vars are missing, or if a call fails, we log and fall
 * back to whatever other providers did succeed.
 *
 * Non-discovery lookups (name/linkedin/email) still hit only Parallel.ai
 * via `buildSearchPlan`.
 *
 * Docs: https://docs.parallel.ai, https://developer.unipile.com,
 * https://docs.exa.ai
 */
const PARALLEL_SEARCH_URL = "https://api.parallel.ai/v1beta/search";
const PLANNER_MODEL = process.env.OPENAI_MODEL ?? "gpt-4o-2024-08-06";
// How many planner-generated queries to pack into each Parallel.ai request.
// Small batches = more concurrent calls = broader fan-out, at the cost of
// more HTTP round-trips. 5 is a compromise that keeps latency under the
// 60s budget while still hitting ~3-4 concurrent requests for a 15-query plan.
const QUERIES_PER_REQUEST = 5;

// Unipile LinkedIn search. DSN (subdomain + port) is per-tenant and set
// at account creation, e.g. "api8.unipile.com:13851". The account id is
// the default Centinel LinkedIn account; overridable via env for tests.
const UNIPILE_LINKEDIN_SEARCH_PATH = "/api/v1/linkedin/search";
const UNIPILE_ACCOUNT_ID =
  process.env.UNIPILE_ACCOUNT_ID ?? "8KMvZvHSQa6owclhc24iSA";
// LinkedIn Classic caps people search at 50 results per request.
const UNIPILE_LINKEDIN_LIMIT = 50;

// Exa People Search. The "people" category replaced "linkedin" in Dec 2025
// and now searches Exa's 1B+ indexed profiles via hybrid retrieval (fine-
// tuned embeddings + Exa Search). Best consumed with natural-language
// queries rather than operators.
const EXA_SEARCH_URL = "https://api.exa.ai/search";
const EXA_PEOPLE_LIMIT = 25;

type ParallelSearchResult = {
  url: string;
  title?: string;
  excerpt?: string;
  excerpts?: string[];
  published_date?: string;
};

type ParallelSearchResponse = {
  results: ParallelSearchResult[];
};

// Subset of the Unipile Classic People search item we actually use. The
// full payload has many more fields; we store it in `raw` for the synth
// layer to dig into later.
type UnipilePersonSearchResult = {
  object: "SearchResult";
  type: "PEOPLE";
  id: string;
  public_identifier?: string | null;
  public_profile_url?: string | null;
  profile_url?: string | null;
  profile_picture_url?: string | null;
  name?: string | null;
  first_name?: string;
  last_name?: string;
  headline?: string;
  location?: string | null;
  industry?: string | null;
  network_distance?: string;
  connections_count?: number;
  followers_count?: number;
  current_positions?: Array<{
    company?: string;
    role?: string;
    location?: string | null;
    description?: string | null;
    industry?: string[];
  }>;
};

type UnipileLinkedinSearchResponse = {
  object: "LinkedinSearch";
  items: Array<UnipilePersonSearchResult | { object: string; type: string }>;
  cursor: string | null;
};

// Subset of Exa's person-category search result we use. The full response
// includes much more (entities, highlights, favicon, image, etc.) — we
// preserve it in `raw` for the synth layer.
type ExaPersonEntity = {
  id?: string;
  type?: "person";
  properties?: {
    name?: string | null;
    location?: string | null;
    workHistory?: Array<{
      company?: string | null;
      role?: string | null;
      start?: string | null;
      end?: string | null;
    }>;
  };
};

type ExaSearchResult = {
  title?: string | null;
  url: string;
  id?: string;
  publishedDate?: string | null;
  author?: string | null;
  score?: number;
  text?: string;
  highlights?: string[];
  summary?: string;
  entities?: Array<ExaPersonEntity | { type?: string }>;
};

type ExaSearchResponse = {
  results?: ExaSearchResult[];
  requestId?: string;
  resolvedSearchType?: string;
};

// Normalized shape that all three providers map into before being written
// as signal rows. Keeps the insertion loop source-agnostic.
type SignalCandidate = {
  url: string;
  source: string;
  title?: string;
  snippet: string;
  publishedAt?: number;
  raw: unknown;
};

export const runSearch = internalAction({
  args: { lookupId: v.id("lookups") },
  handler: async (ctx, { lookupId }) => {
    const apiKey = process.env.PARALLEL_API_KEY;
    if (!apiKey) {
      await ctx.runMutation(internal.lookups.setStatus, {
        lookupId,
        status: "error",
        error: "PARALLEL_API_KEY not set in Convex environment",
      });
      return;
    }

    // Read the lookup row to get the original input. We do this with a
    // fresh runQuery so the action stays stateless.
    const lookup = await ctx.runQuery(internal.lookups._getLookup, {
      lookupId,
    });
    if (!lookup) return;

    await ctx.runMutation(internal.lookups.setStatus, {
      lookupId,
      status: "searching",
    });

    // Build an objective + a fan-out of search queries.
    //
    //  - For name/linkedin/email, one objective with ~4 hand-tuned queries
    //    is enough; we issue a single Parallel.ai call.
    //  - For "query" (discovery), the LLM planner emits three distinct
    //    query sets (web, LinkedIn boolean, Exa natural language) which
    //    we fan out to three providers concurrently:
    //      · Parallel.ai in chunked batches (web search)
    //      · Unipile LinkedIn search, one call per keyword string
    //      · Exa People Search, one call per natural-language query
    //    Results from all three streams are merged, deduped by URL, and
    //    written as signals.
    let results: SignalCandidate[];
    try {
      if (lookup.inputType === "query") {
        const openaiApiKey = process.env.OPENAI_API_KEY;
        if (!openaiApiKey) {
          await ctx.runMutation(internal.lookups.setStatus, {
            lookupId,
            status: "error",
            error: "OPENAI_API_KEY not set in Convex environment",
          });
          return;
        }

        const plan = await planDiscoverySearch(openaiApiKey, lookup.input);
        const batches = chunk(plan.queries, QUERIES_PER_REQUEST);

        const [parallelCandidates, unipileCandidates, exaCandidates] =
          await Promise.all([
            Promise.all(
              batches.map((batch) =>
                callParallelSearch(apiKey, plan.objective, batch),
              ),
            ).then((batched) => batched.flat().map(parallelToSignal)),
            runUnipileLinkedinFanOut(plan.linkedin_queries),
            runExaPeopleFanOut(plan.exa_queries),
          ]);

        results = dedupeSignalsByUrl([
          ...parallelCandidates,
          ...unipileCandidates,
          ...exaCandidates,
        ]);
      } else {
        const { objective, queries } = buildSearchPlan(
          lookup.inputType,
          lookup.input,
        );
        const raw = await callParallelSearch(apiKey, objective, queries);
        results = raw.map(parallelToSignal);
      }
    } catch (err) {
      await ctx.runMutation(internal.lookups.setStatus, {
        lookupId,
        status: "error",
        error: (err as Error).message,
      });
      return;
    }

    // Insert all signals concurrently. Per-signal try/catch via allSettled
    // so that one bad row (oversized raw payload, unexpected field, etc.)
    // doesn't kill the whole pipeline — we log the offender and move on.
    const inserts = await Promise.allSettled(
      results.map((s) =>
        ctx.runMutation(internal.lookups.insertSignal, {
          lookupId,
          source: s.source,
          sourceUrl: s.url || undefined,
          title: s.title || undefined,
          snippet: s.snippet || " ",
          publishedAt: s.publishedAt,
          raw: safeRawForConvex(s.raw),
        }),
      ),
    );
    for (let i = 0; i < inserts.length; i++) {
      const outcome = inserts[i];
      if (outcome.status === "rejected") {
        const s = results[i];
        console.error(
          `insertSignal failed for ${s.source} ${s.url}:`,
          outcome.reason,
          { titleLen: s.title?.length ?? 0, snippetLen: s.snippet.length },
        );
      }
    }

    await ctx.runMutation(internal.lookups.setStatus, {
      lookupId,
      status: "resolving",
    });

    // Hand off to the synthesis layer. For now this is a stub; the next
    // milestone wires in Claude with structured output.
    await ctx.scheduler.runAfter(0, internal.synth.synthesize, { lookupId });
  },
});

// ─── helpers ───────────────────────────────────────────────────────────────

// Query-type (discovery) lookups go through `planDiscoverySearch` instead —
// the hard-coded plan below only covers deterministic name/linkedin/email
// resolution where the target is already known.
function buildSearchPlan(
  inputType: "name" | "linkedin" | "email",
  input: string,
): { objective: string; queries: string[] } {
  switch (inputType) {
    case "linkedin":
      return {
        objective: `Resolve the identity behind the LinkedIn profile ${input}. Find their X/Twitter, GitHub, recent talks, podcasts, news mentions, and anything posted in the last 90 days.`,
        queries: [
          `${input}`,
          `${input} site:twitter.com OR site:x.com`,
          `${input} site:github.com`,
          `${input} podcast OR interview OR talk`,
        ],
      };
    case "email":
      return {
        objective: `Identify the person behind the email ${input}. Find their professional profiles, current role, and recent public activity.`,
        queries: [`"${input}"`, `${input.split("@")[0]} site:linkedin.com`],
      };
    case "name":
    default:
      return {
        objective: `Build a research dossier on ${input}. Find their LinkedIn, X, GitHub, recent posts, role, company, and any public activity in the last 90 days.`,
        queries: [
          `${input} LinkedIn`,
          `${input} site:twitter.com OR site:x.com`,
          `${input} site:github.com`,
          `${input} interview OR podcast OR talk`,
          `${input} news 2026`,
        ],
      };
  }
}

// ─── Discovery planning (query-type lookups) ──────────────────────────────

// Schema for the LLM planner. Using structured output means the model cannot
// sneak in a conversational preamble ("Here are 15 queries:") — we receive
// just the fields below, with no surrounding prose to strip.
const DiscoveryPlanSchema = z.object({
  objective: z
    .string()
    .describe(
      "A single-sentence research objective for Parallel.ai, describing the kind of human the user wants to find. Written in the imperative.",
    ),
  queries: z
    .array(z.string())
    .min(8)
    .max(20)
    .describe(
      "12 to 20 diverse web search queries that, run in parallel, maximize the chance of surfacing real named humans matching the user's description.",
    ),
  linkedin_queries: z
    .array(z.string())
    .min(3)
    .max(6)
    .describe(
      "3 to 6 LinkedIn-optimized keyword strings for the Unipile LinkedIn Classic people search. Each string is sent verbatim as LinkedIn's KEYWORDS filter, so it must use LinkedIn boolean syntax (AND, OR, NOT, quoted phrases) — not site: or other web operators. Each string should encode a different angle (role + location, role + stage, role + trait, etc.) to maximize coverage across runs.",
    ),
  exa_queries: z
    .array(z.string())
    .min(3)
    .max(6)
    .describe(
      "3 to 6 natural-language queries for Exa's People Search (`category: \"people\"`, which indexes 1B+ public profiles). Written as plain English descriptions like 'VP of Product at Microsoft in Seattle' or 'pre-seed B2C founders in San Francisco active on LinkedIn' — NOT Google operators, NOT LinkedIn booleans. Exa's retrieval is semantic, so conversational phrasing outperforms keyword soup. Each query should target a different angle.",
    ),
});

async function planDiscoverySearch(
  openaiApiKey: string,
  input: string,
): Promise<{
  objective: string;
  queries: string[];
  linkedin_queries: string[];
  exa_queries: string[];
}> {
  const client = new OpenAI({ apiKey: openaiApiKey });

  const systemPrompt = [
    "You are Centinel's search planner. The user describes a kind of person they want to find (e.g. 'pre-seed B2C founders in SF who are active on LinkedIn, reputation of being cool'). You return a research objective and THREE fan-outs of search queries, each in a different style because each targets a different retrieval engine.",
    "",
    "GENERAL RULES",
    "1. Return ONLY the fields in the schema. No preamble, no commentary, no opener like 'Here are the queries:'.",
    "2. Each query in any fan-out should attack the problem from a different angle. Do NOT restate the raw input verbatim.",
    "3. Queries should be specific. A good query combines 2 to 4 concrete constraints (role, geography, stage, trait, vertical, etc.).",
    "4. The three fan-outs are NOT translations of each other. Each is written in the style its engine wants: operators for web search, booleans for LinkedIn, natural language for Exa.",
    "",
    "WEB QUERIES (field: `queries`) — 12 to 20 items",
    "These run against Parallel.ai's web search. Use Google search operators freely: site:, intitle:, inurl:, quoted phrases, OR. Cover a wide mix of angles:",
    "   - LinkedIn people search (site:linkedin.com/in + keywords, role, location)",
    "   - X/Twitter bios and posts (site:twitter.com OR site:x.com)",
    "   - Startup databases: Crunchbase, PitchBook, Dealroom, Tracxn",
    "   - Accelerator and incubator portfolios: Y Combinator, Techstars, 500, On Deck, South Park Commons, AI Grant, Neo",
    "   - VC portfolio pages (site:a16z.com, site:sequoiacap.com, site:ycombinator.com, etc.)",
    "   - Product Hunt, Indie Hackers, Hacker News 'Show HN' and 'Who is hiring'",
    "   - Podcasts and interviews (20VC, Lenny's Podcast, Acquired, This Week in Startups)",
    "   - News coverage: TechCrunch, The Information, Axios Pro, Business Insider",
    "   - Conference speaker lists and meetup pages",
    "   - GitHub profiles and README bios (site:github.com)",
    "   - Substack / Medium / personal blogs",
    "Vary synonyms for the role (founder, cofounder, CEO, building, head of, VP, leading). If the user specifies geography, stage, or traits, encode them explicitly.",
    "",
    "LINKEDIN QUERIES (field: `linkedin_queries`) — 3 to 6 items",
    "These are sent verbatim as LinkedIn's KEYWORDS filter via Unipile's LinkedIn Classic people search. LinkedIn Classic's parser is VERY limited — it rejects complex queries as 'content too large' even when they're short. Rules:",
    "   - MAXIMUM 2 top-level AND clauses per query string. Three is the hard ceiling, and only if each clause is a single word. A query like '(\"pre-seed\" OR \"preseed\") AND founder AND (\"San Francisco\" OR \"Bay Area\") AND (consumer OR B2C)' WILL be rejected — it has 4 AND clauses and LinkedIn 400s it.",
    "   - Prefer fewer constraints across MORE queries. It's better to emit 6 focused queries of 1-2 clauses each than 3 kitchen-sink queries that LinkedIn refuses to run.",
    "   - Good examples:",
    "       · 'head of marketing AND (B2C OR consumer)'",
    "       · 'pre-seed founder AND \"San Francisco\"'",
    "       · '\"head of growth\" AND consumer'",
    "       · 'founder AND (creator OR community)'",
    "   - Do NOT use web operators like site:, intitle:, inurl: — LinkedIn ignores them.",
    "   - DO use LinkedIn boolean syntax where helpful: AND, OR, NOT (capitalized), and quoted phrases. But keep it shallow.",
    "   - Each string should encode a DIFFERENT angle (role + location, role + stage, role + trait, role + vertical). Don't duplicate the same constraint set across queries.",
    "   - Keep each string under ~150 characters.",
    "   - Prefer concrete nouns over soft traits. LinkedIn indexes headlines and titles, not 'vibes'; a 'cool reputation' trait is better encoded as concrete signals (e.g. 'creator' or 'angel').",
    "",
    "EXA QUERIES (field: `exa_queries`) — 3 to 6 items",
    "These run against Exa's People Search (category=people), a hybrid retrieval system over 1B+ indexed public profiles. Rules:",
    "   - Write plain-English descriptions, the way you'd brief a recruiter over Slack. Examples:",
    "       · 'VP of Product at Microsoft in Seattle'",
    "       · 'enterprise sales reps from Microsoft based in EMEA'",
    "       · 'pre-seed B2C founders in San Francisco active on LinkedIn and X'",
    "       · 'design engineers who used to work at Figma and now run their own startup'",
    "   - Do NOT use boolean operators (AND/OR/NOT), site: prefixes, or quotation marks — Exa's embeddings read them as literal tokens and accuracy drops.",
    "   - Do NOT translate the LinkedIn boolean query into English; write fresh queries optimized for semantic retrieval. A single well-phrased sentence per query beats a kitchen-sink constraint list.",
    "   - Each query should target a different angle: one might emphasize role+company, another role+geography, another trait+vertical, another transition/career-move signal.",
  ].join("\n");

  const completion = await client.chat.completions.parse({
    model: PLANNER_MODEL,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: `Target description: ${input}` },
    ],
    response_format: zodResponseFormat(DiscoveryPlanSchema, "search_plan"),
  });

  const parsed = completion.choices[0]?.message.parsed;
  if (!parsed || parsed.queries.length === 0) {
    // Planner refused or returned nothing — fall back to a minimal plan so
    // the lookup still produces some evidence instead of hard-erroring.
    return {
      objective: `Find people who match this description: ${input}. Return individual humans with their LinkedIn or company affiliation.`,
      queries: [
        input,
        `${input} founder OR cofounder`,
        `${input} site:linkedin.com/in`,
        `${input} site:twitter.com OR site:x.com`,
      ],
      linkedin_queries: [
        input,
        `${input} AND (founder OR cofounder)`,
        `${input} AND ("CEO" OR "head of")`,
      ],
      exa_queries: [
        input,
        `people matching: ${input}`,
        `founders and leaders matching: ${input}`,
      ],
    };
  }
  return parsed;
}

// ─── Parallel.ai call + result helpers ────────────────────────────────────

async function callParallelSearch(
  apiKey: string,
  objective: string,
  queries: string[],
): Promise<ParallelSearchResult[]> {
  let response: Response;
  try {
    response = await fetch(PARALLEL_SEARCH_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
      },
      body: JSON.stringify({
        objective,
        search_queries: queries,
        mode: "fast",
      }),
    });
  } catch (err) {
    throw new Error(`Parallel fetch failed: ${(err as Error).message}`);
  }

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`Parallel ${response.status}: ${text.slice(0, 500)}`);
  }

  const data = (await response.json()) as ParallelSearchResponse;
  return data.results ?? [];
}

function parallelToSignal(r: ParallelSearchResult): SignalCandidate {
  const snippet =
    r.excerpt ?? (r.excerpts && r.excerpts.join("\n\n")) ?? r.title ?? "";
  return {
    url: r.url,
    source: classifySource(r.url),
    title: r.title,
    snippet,
    publishedAt: r.published_date
      ? Date.parse(r.published_date) || undefined
      : undefined,
    raw: r,
  };
}

// ─── Unipile LinkedIn search (query-type lookups) ─────────────────────────

// Fan out `linkedin_queries` against Unipile's Classic People search, one
// call per keyword string. Concurrent via Promise.all. Best-effort: if the
// env isn't configured or the provider errors, we log and return [] rather
// than failing the whole lookup, since Parallel.ai still produces results.
async function runUnipileLinkedinFanOut(
  keywordQueries: string[],
): Promise<SignalCandidate[]> {
  const dsn = process.env.UNIPILE_DSN;
  const apiKey = process.env.UNIPILE_API_KEY;
  if (!dsn || !apiKey) {
    console.warn(
      "Unipile: UNIPILE_DSN or UNIPILE_API_KEY not set, skipping LinkedIn search fan-out.",
    );
    return [];
  }
  if (keywordQueries.length === 0) return [];

  const settled = await Promise.allSettled(
    keywordQueries.map((keywords) =>
      callUnipileLinkedinSearch(
        dsn,
        apiKey,
        UNIPILE_ACCOUNT_ID,
        simplifyLinkedinKeywords(keywords),
      ),
    ),
  );

  const out: SignalCandidate[] = [];
  for (let i = 0; i < settled.length; i++) {
    const s = settled[i];
    if (s.status === "fulfilled") {
      for (const item of s.value) {
        const mapped = unipileToSignal(item);
        if (mapped) out.push(mapped);
      }
    } else {
      console.error(
        `Unipile LinkedIn search failed for query "${keywordQueries[i]}":`,
        s.reason,
      );
    }
  }
  return out;
}

async function callUnipileLinkedinSearch(
  dsn: string,
  apiKey: string,
  accountId: string,
  keywords: string,
): Promise<UnipilePersonSearchResult[]> {
  const url =
    `https://${dsn}${UNIPILE_LINKEDIN_SEARCH_PATH}` +
    `?account_id=${encodeURIComponent(accountId)}&limit=${UNIPILE_LINKEDIN_LIMIT}`;

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-KEY": apiKey,
      },
      body: JSON.stringify({
        api: "classic",
        category: "people",
        keywords,
      }),
    });
  } catch (err) {
    throw new Error(`Unipile fetch failed: ${(err as Error).message}`);
  }

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`Unipile ${response.status}: ${text.slice(0, 500)}`);
  }

  const data = (await response.json()) as UnipileLinkedinSearchResponse;
  // The search endpoint can return PEOPLE, COMPANY, POST, or JOB items —
  // we only keep the PEOPLE ones for the discovery pipeline.
  return (data.items ?? []).filter(
    (it): it is UnipilePersonSearchResult =>
      (it as UnipilePersonSearchResult).type === "PEOPLE",
  );
}

// LinkedIn Classic's keyword parser rejects queries with too many top-level
// AND clauses as `errors/content_too_large`, regardless of byte size — we
// saw this fire on a 92-char query with 5 ANDs. The planner is prompted to
// stay under 2-3 clauses, but LLMs drift. This is a cheap belt-and-braces
// trim: if a query has more than 3 space-separated `AND` clauses, keep
// only the first 3 (which, per the prompt, are the most important ones —
// role, then location/stage, then vertical).
//
// Splitting on ` AND ` is crude for deeply nested expressions like
// `(A AND B) OR C`, but LLMs rarely generate those for keyword searches,
// and the worst case is that we truncate one extra clause on an odd query,
// which is strictly better than the API rejecting the whole thing.
function simplifyLinkedinKeywords(keywords: string): string {
  const MAX_AND_CLAUSES = 3;
  const parts = keywords.split(/\s+AND\s+/);
  if (parts.length <= MAX_AND_CLAUSES) return keywords;
  return parts.slice(0, MAX_AND_CLAUSES).join(" AND ");
}

function unipileToSignal(
  item: UnipilePersonSearchResult,
): SignalCandidate | null {
  const url = item.public_profile_url ?? item.profile_url ?? undefined;
  if (!url) return null;

  const name =
    item.name ??
    [item.first_name, item.last_name].filter(Boolean).join(" ").trim() ??
    undefined;

  const currentPos = item.current_positions?.[0];
  const roleAtCompany =
    currentPos?.role && currentPos?.company
      ? `${currentPos.role} at ${currentPos.company}`
      : currentPos?.role ?? currentPos?.company ?? undefined;

  const snippetParts = [
    item.headline,
    roleAtCompany,
    item.location,
    item.industry,
  ].filter((p): p is string => Boolean(p && p.length > 0));

  return {
    url,
    source: "linkedin",
    title: name || undefined,
    snippet: snippetParts.join(" · "),
    raw: item,
  };
}

// ─── Exa People Search (query-type lookups) ───────────────────────────────

// Fan out `exa_queries` against Exa's People Search, one call per natural-
// language query. Concurrent via Promise.allSettled. Best-effort: if the
// env isn't configured or the provider errors, log and return [] rather
// than failing the whole lookup.
async function runExaPeopleFanOut(
  queries: string[],
): Promise<SignalCandidate[]> {
  const apiKey = process.env.EXA_API_KEY;
  if (!apiKey) {
    console.warn(
      "Exa: EXA_API_KEY not set, skipping Exa People Search fan-out.",
    );
    return [];
  }
  if (queries.length === 0) return [];

  const settled = await Promise.allSettled(
    queries.map((query) => callExaPeopleSearch(apiKey, query)),
  );

  const out: SignalCandidate[] = [];
  for (let i = 0; i < settled.length; i++) {
    const s = settled[i];
    if (s.status === "fulfilled") {
      for (const item of s.value) {
        const mapped = exaToSignal(item);
        if (mapped) out.push(mapped);
      }
    } else {
      console.error(
        `Exa People Search failed for query "${queries[i]}":`,
        s.reason,
      );
    }
  }
  return out;
}

async function callExaPeopleSearch(
  apiKey: string,
  query: string,
): Promise<ExaSearchResult[]> {
  let response: Response;
  try {
    response = await fetch(EXA_SEARCH_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
      },
      body: JSON.stringify({
        query,
        category: "people",
        numResults: EXA_PEOPLE_LIMIT,
        // Ask for a text excerpt plus query-anchored highlights so the
        // synth layer has something meaty to cite — without pulling the
        // full page of every result (which gets expensive fast).
        contents: {
          text: { maxCharacters: 800 },
          highlights: { query, maxCharacters: 300 },
        },
      }),
    });
  } catch (err) {
    throw new Error(`Exa fetch failed: ${(err as Error).message}`);
  }

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`Exa ${response.status}: ${text.slice(0, 500)}`);
  }

  const data = (await response.json()) as ExaSearchResponse;
  return data.results ?? [];
}

function exaToSignal(item: ExaSearchResult): SignalCandidate | null {
  if (!item.url) return null;

  // Prefer the structured person entity name over the page title — page
  // titles often include marketing suffixes ("| LinkedIn", "— Twitter").
  const personEntity = item.entities?.find(
    (e) => (e as ExaPersonEntity).type === "person",
  ) as ExaPersonEntity | undefined;
  const title = personEntity?.properties?.name ?? item.title ?? undefined;

  // Build snippet from highlights first (query-anchored, tight), then fall
  // back to the page-text excerpt, then to whatever the entity says.
  const snippetFromHighlights = item.highlights?.length
    ? item.highlights.join("\n\n")
    : undefined;
  const snippetFromText = item.text?.slice(0, 600);
  const snippetFromEntity = personEntity?.properties
    ? [
        personEntity.properties.location,
        personEntity.properties.workHistory?.[0]?.role &&
        personEntity.properties.workHistory?.[0]?.company
          ? `${personEntity.properties.workHistory[0].role} at ${personEntity.properties.workHistory[0].company}`
          : undefined,
      ]
        .filter(Boolean)
        .join(" · ")
    : undefined;

  const snippet =
    snippetFromHighlights ?? snippetFromText ?? snippetFromEntity ?? "";

  const publishedAt = item.publishedDate
    ? Date.parse(item.publishedDate) || undefined
    : undefined;

  return {
    url: item.url,
    // Let classifySource tag LinkedIn URLs as "linkedin", X as "x", etc.
    // Anything else (personal sites, news) falls back to the hostname,
    // which is still more useful than a generic "exa" label.
    source: classifySource(item.url),
    title: title ?? undefined,
    snippet,
    publishedAt,
    raw: item,
  };
}

// ─── Shared utilities ─────────────────────────────────────────────────────

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// Both Parallel.ai (across its batched calls) and Unipile (across keyword
// variants) can surface the same URL twice. Dedupe so downstream synthesis
// doesn't see the same page multiple times (which would waste tokens and
// skew talking-point frequency). Entries without a URL are dropped — they
// can't be cited as evidence anyway.
function dedupeSignalsByUrl(results: SignalCandidate[]): SignalCandidate[] {
  const seen = new Set<string>();
  const out: SignalCandidate[] = [];
  for (const r of results) {
    if (!r.url || seen.has(r.url)) continue;
    seen.add(r.url);
    out.push(r);
  }
  return out;
}

// Convex's `v.any()` validator only accepts strictly JSON-serializable
// values — no nested `undefined`, no `Date`, no functions, no circular
// references. And while per-document size caps are 1MB, we don't want a
// single bloated `raw` payload (Exa can return the full page text, Parallel
// can return massive excerpt arrays) to either eat the document budget or
// hit an internal value-size check.
//
// Round-trip through JSON.stringify to normalize, then if the serialized
// form is bigger than MAX_RAW_BYTES, drop `text` / `excerpts` / large
// string fields and retry. If it's still too big, store just the URL.
const MAX_RAW_BYTES = 32_000;
function safeRawForConvex(raw: unknown): unknown {
  if (raw === undefined || raw === null) return undefined;

  let normalized: unknown;
  try {
    normalized = JSON.parse(JSON.stringify(raw));
  } catch {
    // Circular reference or similar — we can't store this as-is.
    return { _unserializable: true };
  }

  const size = byteLen(normalized);
  if (size <= MAX_RAW_BYTES) return normalized;

  // Too big. Strip the worst offenders (long text bodies) and retry.
  if (normalized && typeof normalized === "object") {
    const obj = normalized as Record<string, unknown>;
    for (const key of ["text", "excerpt", "excerpts", "summary", "highlights"]) {
      if (key in obj) obj[key] = undefined;
    }
    // JSON.stringify drops undefineds; round-trip again to normalize.
    const pruned = JSON.parse(JSON.stringify(obj));
    if (byteLen(pruned) <= MAX_RAW_BYTES) return pruned;
  }

  // Still too big — fall back to a minimal reference with just the URL.
  if (normalized && typeof normalized === "object") {
    const obj = normalized as Record<string, unknown>;
    return {
      _truncated: true,
      url: obj.url ?? obj.public_profile_url ?? obj.profile_url ?? undefined,
      source: obj.source ?? undefined,
      originalBytes: size,
    };
  }
  return { _truncated: true, originalBytes: size };
}

function byteLen(value: unknown): number {
  try {
    return new TextEncoder().encode(JSON.stringify(value)).length;
  } catch {
    return Number.POSITIVE_INFINITY;
  }
}

function classifySource(url: string): string {
  try {
    const host = new URL(url).hostname.replace(/^www\./, "");
    if (host.includes("linkedin.com")) return "linkedin";
    if (host.includes("twitter.com") || host.includes("x.com")) return "x";
    if (host.includes("github.com")) return "github";
    if (host.includes("youtube.com") || host.includes("youtu.be")) return "youtube";
    if (host.includes("medium.com") || host.includes("substack.com")) return "blog";
    return host;
  } catch {
    return "web";
  }
}
